services:
  fbla-frontend:
    command: "web"
    image: git.devdoes.work/devaine/fbla-cs-competition:app
    ports:
      - ${FRONTEND_PORT}:3000

  fbla-api:
    command: "api" 
    image: git.devdoes.work/devaine/fbla-cs-competition:app
    environment:
      AI_API_KEY: ${AI_API_KEY}
    ports:
      - ${API_PORT}:8000
